
const product = [
    {
        "southIndian":
            [
                {
                    "_id": "632dfa7d1a1a42f7f2290c5e",
                    "name": "Eru",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/47bewwwu",
                    "price": 40,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 30,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c61",
                    "name": "Kwacoco Bible",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/4mvpxf5t",
                    "price": 12,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 3.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c62",
                    "name": "Koki Beans",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/ybsrksjn",
                    "price": 22,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 4.0,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c63",
                    "name": "Ekpang",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/4ea93kcr",
                    "price": 15,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 1.2,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 2,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c64",
                    "name": "kati-kati",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/4eacv9jx",
                    "price": 12,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 3.5,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c60",
                    "name": "Egusi Pudding",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/47bewwwu",
                    "price": 23,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 2.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 20,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c5f",
                    "name": "Achu",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/bdfarsrr",
                    "price": 10,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c67",
                    "name": "Corn Porridge",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/2s43fxyp",
                    "price": 6,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 2.13,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c65",
                    "name": "Egusi Soup",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/47bewwwu",
                    "price": 16,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 4.40,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 15,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c66",
                    "name": "Bongo Tchobi",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": "https://tinyurl.com/5aydwh3c",
                    "price": 13,
                    "platesAvailable": 4,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    'rating': 3.0,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 18,
                    'desc': 'Eru is a soup from Cameroon. It is a specialty of the Bayangi people, of the Manyu region in southwestern Cameroon'
                }
            ]
    },
    {
        "indianfood":
            [
                {
                    "_id": "532dfa7d1a1a42f7f2290c61",
                    "name": "Balu shahi",
                    "ingredients": "Maida flour, yogurt, oil, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/02ImEep-xqnaxF1o426ui-QDFhqA3r7TAdRhdDt8uc4/rs:fit:1200:1180:1/g:ce/aHR0cHM6Ly8xLmJw/LmJsb2dzcG90LmNv/bS8tLURETVpzWTNP/bnMvVzlMdUhlQS0y/TUkvQUFBQUFBQUFP/LVUvRUFBNUtVVHUz/ZTBxSUNLb0VuNWhw/akJKM0tJZ3A0WlZB/Q0xjQkdBcy9zMTYw/MC9EU0NfMDcwMC5K/UEc',
                    "diet": "vegetarian",
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "region": "East",
                    "price": 400,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                },
                {
                    "_id": "3648732bc736c324783b78",
                    "name": "Boondi",
                    "ingredients": "Gram flour, ghee, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/ah66GEiN0fm4yc46twg-zWrjR9WQ4kXtG7eON6wyRqA/rs:fit:1024:683:1/g:ce/aHR0cHM6Ly93d3cu/YXJjaGFuYXNraXRj/aGVuLmNvbS9pbWFn/ZXMvYXJjaGFuYXNr/aXRjaGVuLzEtQXV0/aG9yL1Nhc21pdGEv/U3dlZXRfQm9vbmRp/X19NZWV0aGlfQm9v/bmRpLmpwZw',
                    "diet": "vegetarian",
                    "prep_time": 80,
                    "cook_time": 30,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Rajasthan",
                    "price": 500,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "West"
                },
                {
                    "_id": "632dfa7d1a1a42f7f2290c5q",
                    "name": "Gajar ka halwa",
                    "ingredients": "Carrots, milk, sugar, ghee, cashews, raisins",
                    "imageUrl": 'https://imgs.search.brave.com/93IL3XkID17v2OI03uNY1eGWH3k5-B4AvMTSSL1KTI8/rs:fit:1200:1200:1/g:ce/aHR0cDovL3doYXRz/Y29va2luZ21vbS5p/bi93cC1jb250ZW50/L3VwbG9hZHMvMjAx/My8wMS9nYWphci1r/YS1oYWx3YS5qcGc',
                    "diet": "vegetarian",
                    "prep_time": 15,
                    "cook_time": 60,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Punjab",
                    "price": 730,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "_id": "875a7d1a1a42f7f2290c5q",
                    "name": "Ghevar",
                    "ingredients": "Flour, ghee, kewra, milk, clarified butter, sugar, almonds, pistachio, saffron, green cardamom",
                    "imageUrl": 'https://imgs.search.brave.com/JONj9wSHrc5_WdWI5SaPpMvgog0Ikd5QEOdKiOBgWCY/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly93d3cu/YXJjaGFuYXNraXRj/aGVuLmNvbS9pbWFn/ZXMvYXJjaGFuYXNr/aXRjaGVuLzEtQXV0/aG9yL0RoYXJhL1Jh/amFzdGhhbmlfR2hl/dmFyLmpwZw',
                    "diet": "vegetarian",
                    "prep_time": 15,
                    "cook_time": 30,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Rajasthan",
                    "price": 820,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "West"
                },
                {
                    "_id": "632djkwey5t87432290c5q",
                    "name": "Gulab jamun",
                    "ingredients": "Milk powder, plain flour, baking powder, ghee, milk, sugar, water, rose water",
                    "imageUrl": 'https://imgs.search.brave.com/johRWpak2jN46sB7L6ZzOqkxVPceXlVZ73Film3xboI/rs:fit:631:225:1/g:ce/aHR0cHM6Ly90c2Ux/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5q/SFZPV3dTRkptS200/V1lqb09JUzBRSGFG/ayZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 15,
                    "cook_time": 40,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "price": 350,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "East"
                },
                {
                    "_id": "632873q64tehg290c5q",
                    "name": "Imarti",
                    "ingredients": "Sugar syrup, lentil flour",
                    "imageUrl": 'https://imgs.search.brave.com/Db-zPuXWhTZB_SSZnWr1oDBqjSE9qL-7M7N6AR_IKB0/rs:fit:632:225:1/g:ce/aHR0cHM6Ly90c2U0/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5y/UkkxSHpXMnEycVVZ/SXV5eS1najJBSGFG/aiZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 50,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "West Bengal",
                    "price": 340,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "East"
                },
                {
                    "_id": "632dfa7d1a1a487346gf",
                    "name": "Jalebi",
                    "ingredients": "Maida, corn flour, baking soda, vinegar, curd, water, turmeric, saffron, cardamom",
                    "imageUrl": 'https://imgs.search.brave.com/Ewo_TOWJlh75kb_RxlJ_Xu10oA1ApUqoenBYXxuBUPk/rs:fit:802:225:1/g:ce/aHR0cHM6Ly90c2Uy/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5n/WTdaNkJhblNWdXVf/MFBZVExNNVBRSGFF/WSZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 50,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "_id": "qwyrt7542f7f2290c5q",
                    "name": "Kaju katli",
                    "ingredients": "Cashews, ghee, cardamom, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/1dab6xrm9o1lI_pS0lSmGp-h-TktE4iV0Lnz5U_0_0I/rs:fit:676:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC44/cEl5VURnZzd5U2F2/Y1IyS0hFMTZ3SGFG/TSZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Kalakand",
                    "ingredients": "Milk, cottage cheese, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/1dab6xrm9o1lI_pS0lSmGp-h-TktE4iV0Lnz5U_0_0I/rs:fit:676:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC44/cEl5VURnZzd5U2F2/Y1IyS0hFMTZ3SGFG/TSZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Kheer",
                    "ingredients": "Milk, rice, sugar, dried fruits",
                    "imageUrl": 'https://imgs.search.brave.com/2YD2FtJW0-IJtWfoW4HBEFqdfNR4sEKBJxnzkieSwMM/rs:fit:715:225:1/g:ce/aHR0cHM6Ly90c2Uy/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5Q/ZzF3TFpSTVM0VnV3/WVJiandoaHVnSGFF/NiZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Laddu",
                    "ingredients": "Gram flour, ghee, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/zQBoMQ3q20MHUwYmbyr7Pew7ale0Crf20A6vGr8LS6c/rs:fit:474:225:1/g:ce/aHR0cHM6Ly90c2Uz/Lm1tLmJpbmcubmV0/L3RoP2lkPU9JUC5O/TzJnRE5hSEJGU2VQ/T1g2anEwY3NnSGFI/YSZwaWQ9QXBp',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Lassi",
                    "ingredients": "Yogurt, milk, nuts, sugar",
                    "imageUrl": 'https://imgs.search.brave.com/02ImEep-xqnaxF1o426ui-QDFhqA3r7TAdRhdDt8uc4/rs:fit:1200:1180:1/g:ce/aHR0cHM6Ly8xLmJw/LmJsb2dzcG90LmNv/bS8tLURETVpzWTNP/bnMvVzlMdUhlQS0y/TUkvQUFBQUFBQUFP/LVUvRUFBNUtVVHUz/ZTBxSUNLb0VuNWhw/akJKM0tJZ3A0WlZB/Q0xjQkdBcy9zMTYw/MC9EU0NfMDcwMC5K/UEc',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Nankhatai",
                    "ingredients": "Refined flour, besan, ghee, powdered sugar, yoghurt, green cardamom",
                    "imageUrl": 'https://imgs.search.brave.com/02ImEep-xqnaxF1o426ui-QDFhqA3r7TAdRhdDt8uc4/rs:fit:1200:1180:1/g:ce/aHR0cHM6Ly8xLmJw/LmJsb2dzcG90LmNv/bS8tLURETVpzWTNP/bnMvVzlMdUhlQS0y/TUkvQUFBQUFBQUFP/LVUvRUFBNUtVVHUz/ZTBxSUNLb0VuNWhw/akJKM0tJZ3A0WlZB/Q0xjQkdBcy9zMTYw/MC9EU0NfMDcwMC5K/UEc',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Petha",
                    "ingredients": "Firm white pumpkin, sugar, kitchen lime, alum powder",
                    "imageUrl": 'https://imgs.search.brave.com/02ImEep-xqnaxF1o426ui-QDFhqA3r7TAdRhdDt8uc4/rs:fit:1200:1180:1/g:ce/aHR0cHM6Ly8xLmJw/LmJsb2dzcG90LmNv/bS8tLURETVpzWTNP/bnMvVzlMdUhlQS0y/TUkvQUFBQUFBQUFP/LVUvRUFBNUtVVHUz/ZTBxSUNLb0VuNWhw/akJKM0tJZ3A0WlZB/Q0xjQkdBcy9zMTYw/MC9EU0NfMDcwMC5K/UEc',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                },
                {
                    "name": "Phirni",
                    "ingredients": "Rice, sugar, nuts",
                    "imageUrl": 'https://imgs.search.brave.com/02ImEep-xqnaxF1o426ui-QDFhqA3r7TAdRhdDt8uc4/rs:fit:1200:1180:1/g:ce/aHR0cHM6Ly8xLmJw/LmJsb2dzcG90LmNv/bS8tLURETVpzWTNP/bnMvVzlMdUhlQS0y/TUkvQUFBQUFBQUFP/LVUvRUFBNUtVVHUz/ZTBxSUNLb0VuNWhw/akJKM0tJZ3A0WlZB/Q0xjQkdBcy9zMTYw/MC9EU0NfMDcwMC5K/UEc',
                    "diet": "vegetarian",
                    "prep_time": 10,
                    "cook_time": 20,
                    "flavor_profile": "sweet",
                    "course": "dessert",
                    "state": "Uttar Pradesh",
                    "price": 430,
                    "platesAvailable": 4,
                    'rating': 4.93,
                    'fifth': 70,
                    'fourth': 30,
                    'third': 10,
                    'second': 5,
                    'first': 2,
                    'save': 12,
                    "region": "North"
                }
            ]
    }
]

module.exports = product